# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acfae4ea8b448613978aec76724e3ac1a6d0c38b6b5cdd493d9863ccb3e45cdb1061703b64a0cb8e14942a7acb8be3fec2fd19e4de80bf79ee2ccbb0ad82c0a0

test:
  secret_key_base: c35a8edb90f253860ebf661ce601b1bf18aea0587a5a03ecf11d93a62c05913f523687174b128350d79f321a55061bed367ce91e1594868388aa8326c0c2657c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
